version: '3.7'
services:
    app:
        depends_on:
            - 'box'
        build:
            context: .
        ports:
        - '3000:3000'
        volumes:
            - '.:/onebittwitter_client:cached'
            - 'box:/node_modules'
        environment:
            - SASS_PATH=node_modules:src
        stdin_open: true
        tty: true
        command:  bash start.sh

    box:
        image: busybox
        volumes: 
            - box:/box
volumes:
  box:
